### ISSUE TITLE
java.lang.NoClassDefFoundError: com/amplitude/Amplitude

### ISSUE THREAD

**Issue by adrianboguszewski** [amplitude/Amplitude-Java#98]
## Summary

One of my users is getting java.lang.NoClassDefFoundError: com/amplitude/Amplitude when trying to initialize Amplitude. What may be the reason for that?

OS:
MacOS Ventura 13.6.2 on a MacPro 16 M1 Max
Java:
Runtime version: 17.0.9+7-b1000.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by justin-fiedler** [comment]
@adrianboguszewski I some spent time investigating this issue and found some similar issues that seem to be related to how libraries are added to Jetbrains plugins. I think this is an issue with the Plugin dependency setup rather than the Amplitude SDK.

https://stackoverflow.com/questions/61434438/intellij-plugin-development-class-not-found

I'm curious is this happening for all users or just one?

Thanks!

**Comment by adrianboguszewski** [comment]
@justin-fiedler, thank you for investigating this. According to the issues you mentioned above, the problem should come from mixing Java and Kotlin. But I don't use Java in my project, just Kotlin.

And the problem occurs only for that user. No one else reported this and I can see all data from other users in Amplitude.
